version: "3"
services:
  nginx:
    ports:
      - "3000:80"
  user-service:
    build:
      context: .
      args: 
        NODE_ENV: development
    volumes:
      - ./:/app
      - /app/node_modules
    environment: 
      - NODE_ENV=development
      - MONGO_USER=meryem
      - MONGO_PASSWORD=123456
      - SESSION_SECRET=secretkey

    command: npm run dev

  kafdrop:
    image: obsidiandynamics/kafdrop
    restart: "no"
    environment:
      KAFKA_BROKERCONNECT: "kafka:9092"
    ports:
      - 9011:9000
    depends_on:
      - kafka
 
  kafka:
    image: wurstmeister/kafka:latest
    networks:
      - kafka_network
    links:
      - zookeeper
    ports:
      - 9092:9092
    hostname: 'kafka'
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka   
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CREATE_TOPICS=Users
      - KAFKA_NUM_PARTITIONS=4
      
  mongo: 
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=meryem
      - MONGO_INITDB_ROOT_PASSWORD=123456

networks:
  kafka_network:
    name: userservice_default